name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Inject environment variables from GitHub Secrets
      - name: Inject environment variables
        run: |
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}"              >> .env
          echo "VITE_SUPABASE_PUBLISHABLE_KEY=${{ secrets.VITE_SUPABASE_PUBLISHABLE_KEY }}" >> .env
          echo "VITE_ANILIST_API_URL=${{ secrets.VITE_ANILIST_API_URL }}"       >> .env
          # Stub per Azure Translator (vuoti finché non aggiungi i secrets)
          echo "VITE_AZURE_TRANSLATOR_ENDPOINT="                               >> .env
          echo "VITE_AZURE_TRANSLATOR_KEY="                                    >> .env

      # Setup Node.js and cache dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Lint
      - name: Lint code
        run: npm run lint

      # Type-check with TypeScript
      - name: Type-check
        run: npx tsc --noEmit

      # Run tests
      - name: Run tests
        run: npm test

      # Build production bundle
      - name: Build
        run: npm run build
